{{- if and .Values.ingress.enabled (index .Values.ingress "oauth2-proxy" "enabled") }}
{{- $oauth2 := index .Values.ingress "oauth2-proxy" }}
{{- if not (index $oauth2 "oidc-issuer-url") -}}
{{- fail "ingress.oauth2-proxy.oidc-issuer-url is required when OAuth2 proxy is enabled" -}}
{{- end -}}
{{- if eq (index $oauth2 "client-id") "" -}}
{{- fail "ingress.oauth2-proxy.client-id is required when OAuth2 proxy is enabled" -}}
{{- end -}}
{{- if eq (index $oauth2 "client-secret") "" -}}
{{- fail "ingress.oauth2-proxy.client-secret is required when OAuth2 proxy is enabled" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-oauth2-proxy
    skypilot.co/component: oauth2-proxy
  name: {{ .Release.Name }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-oauth2-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-oauth2-proxy
        skypilot.co/component: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: {{ index .Values.ingress "oauth2-proxy" "image" | default "quay.io/oauth2-proxy/oauth2-proxy:v7.9.0" }}
        imagePullPolicy: IfNotPresent
        args:
        - --provider=oidc
        - --oidc-issuer-url={{ index .Values.ingress "oauth2-proxy" "oidc-issuer-url" }}
        - --email-domain={{ index .Values.ingress "oauth2-proxy" "email-domain" | default "*" }}
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --skip-provider-button=true
        - --reverse-proxy=true
        {{- if (index .Values.ingress "oauth2-proxy" "use-http") }}
        - --cookie-secure=false
        {{- end }}
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ index .Values.ingress "oauth2-proxy" "client-id" | quote }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ index .Values.ingress "oauth2-proxy" "client-secret" | quote }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          {{- if index .Values.ingress "oauth2-proxy" "cookie-secret" }}
          value: {{ index .Values.ingress "oauth2-proxy" "cookie-secret" | quote }}
          {{- else }}
          # Generate a stable random cookie secret if not provided
          # This uses a deterministic hash of the release name and namespace to ensure consistency across upgrades
          value: {{ printf "%s-%s-oauth2-proxy-cookie-secret" .Release.Name .Release.Namespace | sha256sum | trunc 32 | b64enc | quote }}
          {{- end }}
        ports:
        - containerPort: 4180
          protocol: TCP
{{- end }}
